# <mmkolpakov_changes_dz_2>
---
- name: Create node_exporter group
  ansible.builtin.group:
    name: node_exporter
    state: present

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter
    shell: /sbin/nologin
    system: true
    create_home: false

- name: Download Node Exporter binary (Local)
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: '0644'

- name: Unarchive Node Exporter (Local)
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/"
    remote_src: true
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"

- name: Copy Node Exporter binary to target
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    owner: node_exporter
    group: node_exporter
  notify: restart node_exporter

- name: Create systemd service for Node Exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  notify: restart node_exporter

- name: Enable and start Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
# </mmkolpakov_changes_dz_2>
