replicaCount: 1

image:
  repository: ghcr.io/ldest/mfti-course/api
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx-ingress"
  host: "student-7.local"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

db:
  host: "192.168.1.46"
  port: 5000
  name: "api_db"
  user: "api_user"
