import http from 'k6/http';
import { check, sleep } from 'k6';
import { randomString } from 'https://jslib.k6.io/k6-utils/1.6.0/index.js';

// Конфигурация нагрузки
export const options = {
  stages: [
    { duration: '30s', target: 10 },
    { duration: '1m', target: 50 },
    { duration: '2m', target: 200 },
    { duration: '30s', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(95)<200'],
    http_req_failed: ['rate<0.01'],
  },
};

// Конфигурация цели
// Внутренний IP Ingress-контроллера (балансировщика), минуя внешнюю сеть
const BASE_URL = 'http://192.168.1.100:80';
const HOST_HEADER = 'student-7.local';

export default function () {
  const params = {
    headers: {
      'Host': HOST_HEADER,
      'Content-Type': 'application/json',
    },
    tags: { name: 'api' },
  };

  // 20% запросов - Запись
  if (Math.random() < 0.2) {
    const payload = JSON.stringify({
      name: `City-${randomString(8)}`,
      description: `Load test city generated by k6`
    });

    const resPost = http.post(`${BASE_URL}/Cities`, payload, params);

    check(resPost, {
      'POST status is 200/201': (r) => r.status === 200 || r.status === 201,
    });
  }
  // 80% запросов - Чтение
  else {
    const endpoint = Math.random() < 0.5 ? '/Cities' : '/Cities/1';
    const resGet = http.get(`${BASE_URL}${endpoint}`, params);

    check(resGet, {
      'GET status is 200': (r) => r.status === 200,
    });
  }
  sleep(0.5);
}
